/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import hotelbooking.History;

/**
 *
 * @author user
 */
public class Edit extends javax.swing.JFrame {

   History page;
   
   public Edit() {
      initComponents();
   }

   public Edit(String start, String end, String name, String ic, String contact, String email, int roomno, History page) {
      initComponents();

      txtName.setText(name);
      txtIC.setText(ic);
      txtContact.setText(contact);
      txtEmail.setText(email);
      this.page = page;
      cmbDay.setSelectedIndex(Integer.valueOf(start) - 1);
      cmbDuration.setSelectedIndex(((Integer.valueOf(end) - 1) - (Integer.valueOf(start) - 1)) - 1);
      cmbRoomNo.removeAllItems();
      cmbRoomNo.addItem(String.valueOf(roomno));
   }
   


   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      txtContact = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      cmbDuration = new javax.swing.JComboBox<>();
      jLabel6 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      cmbDay = new javax.swing.JComboBox<>();
      jLabel4 = new javax.swing.JLabel();
      txtEmail = new javax.swing.JTextField();
      cmbRoomNo = new javax.swing.JComboBox<>();
      jLabel3 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      txtName = new javax.swing.JTextField();
      txtIC = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      lblError = new javax.swing.JLabel();
      btnConfirm = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jPanel1.setBackground(new java.awt.Color(204, 255, 204));
      jPanel1.setForeground(new java.awt.Color(0, 0, 0));

      jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel2.setText("Start Day :");
      jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      txtContact.setForeground(new java.awt.Color(0, 0, 0));
      txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtContactKeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtContactKeyTyped(evt);
         }
      });

      jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(0, 0, 0));
      jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel7.setText("Email :");
      jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      cmbDuration.setMaximumRowCount(6);
      cmbDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Night", "2 Nights", "3 Nights", "4 Nights", "5 Nights", "6 Nights" }));
      cmbDuration.setToolTipText("");

      jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(0, 0, 0));
      jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel6.setText("IC / Passport :");
      jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(0, 0, 0));
      jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel5.setText("Contact No :");
      jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
      cmbDay.setEnabled(false);

      jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(0, 0, 0));
      jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel4.setText("Name :");
      jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      txtEmail.setForeground(new java.awt.Color(0, 0, 0));

      cmbRoomNo.setMaximumRowCount(20);
      cmbRoomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Check Room ---" }));

      jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(0, 0, 0));
      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel3.setText("RoomNo :");
      jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(0, 0, 0));
      jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel8.setText("Duration :");
      jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      txtName.setForeground(new java.awt.Color(0, 0, 0));

      txtIC.setEditable(false);
      txtIC.setForeground(new java.awt.Color(0, 0, 0));
      txtIC.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtICKeyTyped(evt);
         }
      });

      jLabel1.setBackground(new java.awt.Color(0, 0, 0));
      jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Edit Booking");
      jLabel1.setToolTipText("");
      jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      lblError.setForeground(new java.awt.Color(255, 51, 51));
      lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      btnConfirm.setBackground(new java.awt.Color(204, 255, 153));
      btnConfirm.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
      btnConfirm.setText("Confirm");
      btnConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnConfirm.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConfirmActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                     .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(165, 165, 165))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGap(12, 12, 12)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(cmbRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(36, 36, 36)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))))
            .addContainerGap(35, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel8)
               .addComponent(cmbDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(cmbRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnConfirm)
            .addContainerGap(34, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
      int start = cmbDay.getSelectedIndex() + 1;
      int duration = cmbDuration.getSelectedIndex() + 1;
      int end = duration + start;
      String roomno = cmbRoomNo.getSelectedItem().toString();
      String filepath = roomno.trim() + ".txt";
      String name = txtName.getText();
      String ic = txtIC.getText().trim();
      String contact = txtContact.getText().trim();
      String email = txtEmail.getText().trim();

      String emailRegex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      Pattern emailPattern = Pattern.compile(emailRegex);
      Matcher emailMatcher = emailPattern.matcher(txtEmail.getText());
      
      if (name.isBlank() || ic.isBlank() || contact.isBlank() || email.isBlank()) {
         lblError.setText("Please fill in all the columns");
      } else if (!emailMatcher.find()) {
         JOptionPane.showMessageDialog(this, "Make sure your E-mail is in a correct format (Example: mail@mail.com)", "Email Format Error!", JOptionPane.WARNING_MESSAGE);
      } else {
         
         RoomNo room = new RoomNo(Integer.valueOf(roomno), start, duration, end);
         boolean found = room.roomCheckSelf(roomno, end, ic);
         if (found == true) {
            JOptionPane.showMessageDialog(this, "Dates are overlapping with other customers! Please try again!");
         } else {
            room.editRecord(filepath, String.valueOf(start), String.valueOf(end), name, ic, contact, email);
            this.dispose();
            page.dispose();
            History a = new History();
            a.setVisible(true);
            
         }
      }


   }//GEN-LAST:event_btnConfirmActionPerformed

   private void txtICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtICKeyTyped
      boolean maxchar = txtIC.getText().length() > 12;
      if (maxchar) {
         evt.consume();
      }
   }//GEN-LAST:event_txtICKeyTyped

   private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed
      char c = evt.getKeyChar();
      if (Character.isLetter(c)) {
         txtContact.setEditable(false);
      } else {
         txtContact.setEditable(true);
      }
   }//GEN-LAST:event_txtContactKeyPressed

   private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
      boolean maxno = txtContact.getText().length() > 11;
      if (maxno) {
         evt.consume();
      }
   }//GEN-LAST:event_txtContactKeyTyped

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Edit().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnConfirm;
   private javax.swing.JComboBox<String> cmbDay;
   private javax.swing.JComboBox<String> cmbDuration;
   private javax.swing.JComboBox<String> cmbRoomNo;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JLabel lblError;
   private javax.swing.JTextField txtContact;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtIC;
   private javax.swing.JTextField txtName;
   // End of variables declaration//GEN-END:variables
}
