/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

   private static Scanner x;

   public Login() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jFrame1 = new javax.swing.JFrame();
      jLabel2 = new javax.swing.JLabel();
      lblRegUsername = new javax.swing.JLabel();
      lblRegPassword = new javax.swing.JLabel();
      txtRegUsername = new javax.swing.JTextField();
      txtRegPassword = new javax.swing.JPasswordField();
      btnLoginPage = new javax.swing.JButton();
      btnRegister1 = new javax.swing.JButton();
      btnClear1 = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      btnRegisterPage = new javax.swing.JButton();
      txtLoginUsername = new javax.swing.JTextField();
      btnLogin = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      lblLoginPassword = new javax.swing.JLabel();
      btnLoginClear = new javax.swing.JButton();
      txtLoginPassword = new javax.swing.JPasswordField();
      lblLoginUsername = new javax.swing.JLabel();
      lblErrorLogin = new javax.swing.JLabel();

      jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel2.setBackground(new java.awt.Color(153, 255, 153));
      jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel2.setText("Register Account");
      jLabel2.setToolTipText("");
      jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 255, 51)));
      jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      lblRegUsername.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
      lblRegUsername.setText("Username :");

      lblRegPassword.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
      lblRegPassword.setText("Password :");

      txtRegUsername.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtRegUsernameActionPerformed(evt);
         }
      });

      btnLoginPage.setText("Login Page ⮞");
      btnLoginPage.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginPageActionPerformed(evt);
         }
      });

      btnRegister1.setText("Register");

      btnClear1.setText("Clear");
      btnClear1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnClear1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
      jFrame1.getContentPane().setLayout(jFrame1Layout);
      jFrame1Layout.setHorizontalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jFrame1Layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(btnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnClear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(15, 15, 15))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
            .addGap(141, 141, 141)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addGap(125, 125, 125))
         .addGroup(jFrame1Layout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lblRegUsername)
               .addComponent(lblRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(21, 21, 21)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtRegUsername)
               .addComponent(txtRegPassword))
            .addGap(89, 89, 89))
      );
      jFrame1Layout.setVerticalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jFrame1Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addGap(32, 32, 32)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jFrame1Layout.createSequentialGroup()
                  .addGap(7, 7, 7)
                  .addComponent(lblRegUsername))
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(txtRegUsername)))
            .addGap(18, 18, 18)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jFrame1Layout.createSequentialGroup()
                  .addGap(5, 5, 5)
                  .addComponent(lblRegPassword))
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(txtRegPassword)))
            .addGap(39, 39, 39)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnClear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(38, 38, 38))
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(51, 153, 255));

      jPanel1.setBackground(new java.awt.Color(204, 255, 204));
      jPanel1.setForeground(new java.awt.Color(0, 0, 0));

      btnRegisterPage.setBackground(new java.awt.Color(204, 255, 153));
      btnRegisterPage.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnRegisterPage.setForeground(new java.awt.Color(0, 0, 0));
      btnRegisterPage.setText("Register Page ⮞");
      btnRegisterPage.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegisterPageActionPerformed(evt);
         }
      });

      txtLoginUsername.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtLoginUsernameActionPerformed(evt);
         }
      });

      btnLogin.setBackground(new java.awt.Color(204, 255, 153));
      btnLogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnLogin.setForeground(new java.awt.Color(0, 0, 0));
      btnLogin.setText("Login");
      btnLogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginActionPerformed(evt);
         }
      });

      jLabel1.setBackground(new java.awt.Color(0, 0, 0));
      jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Login Page");
      jLabel1.setToolTipText("");
      jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      lblLoginPassword.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
      lblLoginPassword.setForeground(new java.awt.Color(0, 0, 0));
      lblLoginPassword.setText("Password :");

      btnLoginClear.setBackground(new java.awt.Color(204, 255, 153));
      btnLoginClear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnLoginClear.setForeground(new java.awt.Color(0, 0, 0));
      btnLoginClear.setText("Clear");
      btnLoginClear.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginClearActionPerformed(evt);
         }
      });

      lblLoginUsername.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
      lblLoginUsername.setForeground(new java.awt.Color(0, 0, 0));
      lblLoginUsername.setText("Username :");

      lblErrorLogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      lblErrorLogin.setForeground(new java.awt.Color(255, 51, 51));
      lblErrorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblErrorLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(91, 91, 91)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(lblLoginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
               .addComponent(lblLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtLoginUsername)
               .addComponent(txtLoginPassword))
            .addGap(77, 77, 77))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLoginClear, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnRegisterPage, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(112, 112, 112))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblErrorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lblLoginUsername))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lblLoginPassword))
            .addGap(31, 31, 31)
            .addComponent(lblErrorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnLogin)
               .addComponent(btnLoginClear)
               .addComponent(btnRegisterPage))
            .addContainerGap(19, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void txtRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegUsernameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtRegUsernameActionPerformed

   private void btnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPageActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnLoginPageActionPerformed

   private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnClear1ActionPerformed

   private void btnRegisterPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPageActionPerformed
      Register a = new Register();
      a.setVisible(true);
      this.setVisible(false);
   }//GEN-LAST:event_btnRegisterPageActionPerformed

   private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsernameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtLoginUsernameActionPerformed

   private void btnLoginClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginClearActionPerformed
      txtLoginUsername.setText("");
      txtLoginPassword.setText("");
   }//GEN-LAST:event_btnLoginClearActionPerformed

   private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

      User user = new User(txtLoginUsername.getText(), txtLoginPassword.getText());
      boolean found = false;
      String tempUsername = "";
      String tempPassword = "";
      String Username = user.getUsername();
      String Password = user.getPassword();

      try {

         x = new Scanner(new File("user.txt"));

         while (x.hasNext() && !found) {
            tempUsername = x.nextLine();
            tempPassword = x.nextLine();

            if (tempUsername.trim().equals(Username.trim()) && tempPassword.trim().equals(Password.trim())) {
               found = true;
            }
         }
         
         if (found == true) {
            Room a = new Room();
            a.setVisible(true);
            this.dispose();
            
            for (int i = 1; i < 21; i++) {
               FileWriter fw = new FileWriter(i+".txt", true);
            }      
            
         } else {
         lblErrorLogin.setText("No user account found");
         }

         x.close();
      } catch (IOException e) {
         lblErrorLogin.setText("Error occured: " + e);
      }


   }//GEN-LAST:event_btnLoginActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Login().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnClear1;
   private javax.swing.JButton btnLogin;
   private javax.swing.JButton btnLoginClear;
   private javax.swing.JButton btnLoginPage;
   private javax.swing.JButton btnRegister1;
   private javax.swing.JButton btnRegisterPage;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JLabel lblErrorLogin;
   private javax.swing.JLabel lblLoginPassword;
   private javax.swing.JLabel lblLoginUsername;
   private javax.swing.JLabel lblRegPassword;
   private javax.swing.JLabel lblRegUsername;
   private javax.swing.JPasswordField txtLoginPassword;
   private javax.swing.JTextField txtLoginUsername;
   private javax.swing.JPasswordField txtRegPassword;
   private javax.swing.JTextField txtRegUsername;
   // End of variables declaration//GEN-END:variables
}
