/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import java.text.DecimalFormat;

/**
 *
 * @author user
 */
public class Receipt extends javax.swing.JFrame {

   private static DecimalFormat df2 = new DecimalFormat("#.##");
   public Receipt() {
      initComponents();
   }

   public Receipt(String start, String end, String name, String ic, String contact, String email, int roomno) {
      initComponents();
      int duration = Integer.valueOf(end) - Integer.valueOf(start);
      int subtotal = duration * 350;
      double service = 0.1 * subtotal;
      int tourism = 10 * duration;
      double total = subtotal + service + tourism;
      String roomnumber = "";
      if (roomno > 10) {
         roomnumber = "(Floor 2) - Room "+String.valueOf(roomno) ;
      } else {
      roomnumber= "(Floor 1) - Room "+String.valueOf(roomno) ;
      }
      lblName.setText(name);
      lblIC.setText(ic);
      lblContact.setText(contact);
      lblEmail.setText(email);
      lblRoomNo.setText(roomnumber);
      lblDuration.setText(String.valueOf(duration) + " Nights");
      lblsubtotal.setText("RM " + String.valueOf(subtotal));
      lblservicetax.setText("(10% of SubTotal) - RM " + String.valueOf(df2.format(service)) + " ");
      lbltourismtax.setText("(RM10 per night) - RM " + String.valueOf(df2.format(tourism))+ " ");
      lblTotal.setText("RM "+ String.valueOf(df2.format(total))+ " ");
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      lblName = new javax.swing.JLabel();
      lblIC = new javax.swing.JLabel();
      lblContact = new javax.swing.JLabel();
      lblEmail = new javax.swing.JLabel();
      lblRoomNo = new javax.swing.JLabel();
      lblpricepernight = new javax.swing.JLabel();
      lblDuration = new javax.swing.JLabel();
      lblsubtotal = new javax.swing.JLabel();
      lblservicetax = new javax.swing.JLabel();
      lbltourismtax = new javax.swing.JLabel();
      lblTotal = new javax.swing.JLabel();
      jLabel15 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Receipt");
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Receipt");

      jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setText("_________________________");

      jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(0, 0, 0));
      jLabel3.setText("Name :");

      jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(0, 0, 0));
      jLabel4.setText("IC / Passport No :");

      jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(0, 0, 0));
      jLabel5.setText("Contact No :");

      jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(0, 0, 0));
      jLabel6.setText("Email :");

      jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(0, 0, 0));
      jLabel7.setText("Room No :");

      jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(0, 0, 0));
      jLabel8.setText("Duration :");

      jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(0, 0, 0));
      jLabel9.setText("_________________________");

      jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel10.setForeground(new java.awt.Color(0, 0, 0));
      jLabel10.setText("Price Per Night :");

      jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel11.setForeground(new java.awt.Color(0, 0, 0));
      jLabel11.setText("SubTotal :");

      jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel12.setForeground(new java.awt.Color(0, 0, 0));
      jLabel12.setText("_________________________");

      jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel13.setForeground(new java.awt.Color(0, 0, 0));
      jLabel13.setText("Service Tax :");

      jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
      jLabel14.setForeground(new java.awt.Color(0, 0, 0));
      jLabel14.setText("Tourism Tax :");

      lblName.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblName.setForeground(new java.awt.Color(0, 0, 0));
      lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

      lblIC.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblIC.setForeground(new java.awt.Color(0, 0, 0));
      lblIC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblIC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

      lblContact.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblContact.setForeground(new java.awt.Color(0, 0, 0));
      lblContact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

      lblEmail.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblEmail.setForeground(new java.awt.Color(0, 0, 0));
      lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

      lblRoomNo.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblRoomNo.setForeground(new java.awt.Color(0, 0, 0));
      lblRoomNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

      lblpricepernight.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblpricepernight.setForeground(new java.awt.Color(0, 0, 0));
      lblpricepernight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblpricepernight.setText("RM350.00");

      lblDuration.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblDuration.setForeground(new java.awt.Color(0, 0, 0));
      lblDuration.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblDuration.setText("---");

      lblsubtotal.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
      lblsubtotal.setForeground(new java.awt.Color(0, 0, 0));
      lblsubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblsubtotal.setText("---");

      lblservicetax.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lblservicetax.setForeground(new java.awt.Color(0, 0, 0));
      lblservicetax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblservicetax.setText("---");

      lbltourismtax.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
      lbltourismtax.setForeground(new java.awt.Color(0, 0, 0));
      lbltourismtax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lbltourismtax.setText("---");

      lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      lblTotal.setForeground(new java.awt.Color(0, 0, 0));
      lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lblTotal.setText("---");

      jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      jLabel15.setForeground(new java.awt.Color(0, 0, 0));
      jLabel15.setText("Total :");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(120, 120, 120))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(72, 72, 72)
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(jLabel12)))
            .addGap(75, 75, 75))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(lblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(52, 52, 52)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                 .addComponent(lblIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(lblRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                           .addComponent(lblpricepernight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(lbltourismtax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(lblservicetax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(lblDuration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGap(67, 67, 67))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(lblName))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(lblIC))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(lblContact))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(lblEmail))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(lblRoomNo))
            .addGap(54, 54, 54)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel10)
               .addComponent(lblpricepernight))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel8)
               .addComponent(lblDuration))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel11)
               .addComponent(lblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lblservicetax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel14)
               .addComponent(lbltourismtax))
            .addGap(18, 18, 18)
            .addComponent(jLabel12)
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel15)
               .addComponent(lblTotal))
            .addContainerGap(61, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Receipt().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JLabel lblContact;
   private javax.swing.JLabel lblDuration;
   private javax.swing.JLabel lblEmail;
   private javax.swing.JLabel lblIC;
   private javax.swing.JLabel lblName;
   private javax.swing.JLabel lblRoomNo;
   private javax.swing.JLabel lblTotal;
   private javax.swing.JLabel lblpricepernight;
   private javax.swing.JLabel lblservicetax;
   private javax.swing.JLabel lblsubtotal;
   private javax.swing.JLabel lbltourismtax;
   // End of variables declaration//GEN-END:variables
}
