package hotelbooking;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class Register extends javax.swing.JFrame {

   private static Scanner x;

   public Register() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      btnRegClear = new javax.swing.JButton();
      txtRegUsername = new javax.swing.JTextField();
      btnLoginPage = new javax.swing.JButton();
      lblError = new javax.swing.JLabel();
      lblRegUsername = new javax.swing.JLabel();
      lblRegPassword = new javax.swing.JLabel();
      txtRegPassword = new javax.swing.JPasswordField();
      btnRegister = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(51, 153, 255));

      jPanel1.setBackground(new java.awt.Color(204, 255, 204));

      btnRegClear.setBackground(new java.awt.Color(204, 255, 153));
      btnRegClear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnRegClear.setForeground(new java.awt.Color(0, 0, 0));
      btnRegClear.setText("Clear");
      btnRegClear.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegClearActionPerformed(evt);
         }
      });

      txtRegUsername.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtRegUsernameActionPerformed(evt);
         }
      });

      btnLoginPage.setBackground(new java.awt.Color(204, 255, 153));
      btnLoginPage.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnLoginPage.setForeground(new java.awt.Color(0, 0, 0));
      btnLoginPage.setText("Login Page ⮞");
      btnLoginPage.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginPageActionPerformed(evt);
         }
      });

      lblError.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      lblError.setForeground(new java.awt.Color(255, 51, 51));
      lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      lblRegUsername.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
      lblRegUsername.setForeground(new java.awt.Color(0, 0, 0));
      lblRegUsername.setText("Username :");

      lblRegPassword.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
      lblRegPassword.setForeground(new java.awt.Color(0, 0, 0));
      lblRegPassword.setText("Password :");

      btnRegister.setBackground(new java.awt.Color(204, 255, 153));
      btnRegister.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnRegister.setForeground(new java.awt.Color(0, 0, 0));
      btnRegister.setText("Register");
      btnRegister.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegisterActionPerformed(evt);
         }
      });

      jLabel1.setBackground(new java.awt.Color(0, 0, 0));
      jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Register Account");
      jLabel1.setToolTipText("");
      jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addGap(135, 135, 135)
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                  .addGap(119, 119, 119))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(72, 72, 72)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblRegUsername)
                     .addComponent(lblRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(21, 21, 21)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtRegUsername)
                     .addComponent(txtRegPassword))
                  .addGap(83, 83, 83))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnRegClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(7, 7, 7)
                  .addComponent(lblRegUsername))
               .addComponent(txtRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(5, 5, 5)
                  .addComponent(lblRegPassword))
               .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnRegClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(24, 24, 24))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void txtRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegUsernameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtRegUsernameActionPerformed

   private void btnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPageActionPerformed
      Login a = new Login();
      a.setVisible(true);
      this.dispose();
   }//GEN-LAST:event_btnLoginPageActionPerformed

   private void btnRegClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClearActionPerformed
      txtRegUsername.setText("");
      txtRegPassword.setText("");
   }//GEN-LAST:event_btnRegClearActionPerformed

   private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

      String us = txtRegUsername.getText();
      String pw = String.valueOf(txtRegPassword.getPassword());

      if (us.isBlank() || pw.isBlank()) {
         lblError.setText("Please fill in the columns");
      } else {
         User user = new User(us, pw);
         user.setUsername(us);
         user.setPassword(pw);

         try {
            FileWriter fw = new FileWriter("user.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
            x = new Scanner(new File("user.txt"));
            boolean found = false;
            while (x.hasNext() && !found) {
               String tempUsername = x.nextLine();
               String tempPassword = x.nextLine();
               if (tempUsername.trim().equals(user.getUsername().trim()) 
                       && tempPassword.trim().equals(user.getPassword().trim())) {
                  found = true;
               }
            }
            if (found == true) {
               lblError.setText("User already exists");
            } else {
               bw.write(user.getUsername());
               bw.newLine();
               bw.write(user.getPassword());
               bw.newLine();
               bw.close();
               lblError.setText("Data has been registered");
               txtRegUsername.setText("");
               txtRegPassword.setText("");
            }
         } catch (IOException ex) {
            lblError.setText("Error has occured : " + ex);
         }
      }

   }//GEN-LAST:event_btnRegisterActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Register().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnLoginPage;
   private javax.swing.JButton btnRegClear;
   private javax.swing.JButton btnRegister;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JLabel lblError;
   private javax.swing.JLabel lblRegPassword;
   private javax.swing.JLabel lblRegUsername;
   private javax.swing.JPasswordField txtRegPassword;
   private javax.swing.JTextField txtRegUsername;
   // End of variables declaration//GEN-END:variables
}
