package hotelbooking;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Room extends javax.swing.JFrame {

   private static Scanner x;
   private int rooms[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};

   public Room() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btnGroupDays = new javax.swing.ButtonGroup();
      jPanel2 = new javax.swing.JPanel();
      lblError = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      txtName = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      btnHistory = new javax.swing.JButton();
      jLabel7 = new javax.swing.JLabel();
      txtIC = new javax.swing.JTextField();
      jPanel1 = new javax.swing.JPanel();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      btnCheckRooms = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      txtContact = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      cmbRoomNo = new javax.swing.JComboBox<>();
      txtEmail = new javax.swing.JTextField();
      cmbDay = new javax.swing.JComboBox<>();
      cmbDuration = new javax.swing.JComboBox<>();
      btnAdd = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(51, 153, 255));

      jPanel2.setBackground(new java.awt.Color(204, 255, 204));
      jPanel2.setForeground(new java.awt.Color(0, 0, 0));

      lblError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      lblError.setForeground(new java.awt.Color(255, 51, 51));
      lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel8.setForeground(new java.awt.Color(0, 0, 0));
      jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel8.setText("Duration :");
      jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel2.setText("Start Day :");
      jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel1.setBackground(new java.awt.Color(0, 0, 0));
      jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Add Booking");
      jLabel1.setToolTipText("");
      jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel4.setForeground(new java.awt.Color(0, 0, 0));
      jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel4.setText("Name :");
      jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      btnHistory.setBackground(new java.awt.Color(204, 255, 153));
      btnHistory.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnHistory.setForeground(new java.awt.Color(0, 0, 0));
      btnHistory.setText("Booking History ⮞");
      btnHistory.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnHistoryActionPerformed(evt);
         }
      });

      jLabel7.setForeground(new java.awt.Color(0, 0, 0));
      jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel7.setText("Email :");
      jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      txtIC.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtICKeyTyped(evt);
         }
      });

      jPanel1.setBackground(new java.awt.Color(204, 255, 204));
      jPanel1.setForeground(new java.awt.Color(0, 0, 0));

      jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(0, 0, 0));
      jLabel9.setText("( Floor 1 )");

      jLabel10.setForeground(new java.awt.Color(0, 0, 0));
      jLabel10.setText("Room 1, 2, 3, 4, 5, 6, 7, 8, 9, 10");

      jLabel12.setForeground(new java.awt.Color(0, 0, 0));
      jLabel12.setText("Room 11, 12, 13, 14, 15, 16, 17, 18, 19, 20");

      jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      jLabel11.setForeground(new java.awt.Color(0, 0, 0));
      jLabel11.setText("( Floor 2 )");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel9)
               .addComponent(jLabel10))
            .addGap(18, 18, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel12)
               .addComponent(jLabel11)))
      );

      jLabel6.setForeground(new java.awt.Color(0, 0, 0));
      jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel6.setText("IC / Passport :");
      jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      btnCheckRooms.setBackground(new java.awt.Color(204, 255, 153));
      btnCheckRooms.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnCheckRooms.setForeground(new java.awt.Color(0, 0, 0));
      btnCheckRooms.setText("Check Rooms");
      btnCheckRooms.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCheckRoomsActionPerformed(evt);
         }
      });

      jLabel3.setForeground(new java.awt.Color(0, 0, 0));
      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel3.setText("RoomNo :");
      jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtContactKeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtContactKeyTyped(evt);
         }
      });

      jLabel5.setForeground(new java.awt.Color(0, 0, 0));
      jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel5.setText("Contact No :");
      jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      cmbRoomNo.setMaximumRowCount(20);
      cmbRoomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Check Room ---" }));

      cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

      cmbDuration.setMaximumRowCount(6);
      cmbDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Night", "2 Nights", "3 Nights", "4 Nights", "5 Nights", "6 Nights" }));
      cmbDuration.setToolTipText("");

      btnAdd.setBackground(new java.awt.Color(204, 255, 153));
      btnAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btnAdd.setForeground(new java.awt.Color(0, 0, 0));
      btnAdd.setText("Add Booking");
      btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cmbRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCheckRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                           .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(cmbDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                           .addComponent(txtContact, javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtIC, javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addContainerGap(39, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(39, 39, 39))))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(124, 124, 124)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(88, 88, 88))
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(297, 297, 297)
            .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel8)
                     .addComponent(cmbDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(7, 7, 7)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel3)
                     .addComponent(cmbRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnCheckRooms)))
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnAdd)
            .addGap(18, 18, 18)
            .addComponent(btnHistory)
            .addContainerGap(31, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btnCheckRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckRoomsActionPerformed

      try {

         DefaultComboBoxModel model = (DefaultComboBoxModel) cmbRoomNo.getModel();
         model.removeAllElements();

         for (int i = 0; i < rooms.length; i++) { // Search all room files

            model.addElement(rooms[i]);
            File file = new File((i + 1) + ".txt");
            x = new Scanner(file);

            int start = cmbDay.getSelectedIndex() + 1;
            int duration = cmbDuration.getSelectedIndex() + 1;
            int end = start + duration;
            RoomBooking room = new RoomBooking(start, duration, end);
            boolean found = room.roomCheck(x, end);
            if (found == true) {
               model.removeElement(rooms[i]);
            }

         }

      } catch (IOException ex) {
         lblError.setText("Error has occured : " + ex);
      }


   }//GEN-LAST:event_btnCheckRoomsActionPerformed

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

      String name = txtName.getText();
      String ic = txtIC.getText().trim();
      String contact = txtContact.getText().trim();
      String email = txtEmail.getText().trim();
      RoomBooking roombooking = new RoomBooking(name, ic, contact, email);

      try {

         if (name.isBlank() || ic.isBlank() || contact.isBlank() || email.isBlank()) {
            lblError.setText("Please fill in all the columns");
         } else {

            int start = cmbDay.getSelectedIndex() + 1;
            int duration = cmbDuration.getSelectedIndex() + 1;
            String roomno = cmbRoomNo.getSelectedItem().toString();
            RoomBooking roomdates = new RoomBooking(start, duration, start + duration);
            
            String emailRegex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
            Pattern emailPattern = Pattern.compile(emailRegex);
            Matcher emailMatcher = emailPattern.matcher(txtEmail.getText());
            if (roomno.length() > 2) {
               lblError.setText("Please choose a room first");
            } else if (!emailMatcher.find()) {
               JOptionPane.showMessageDialog(this, "Make sure your E-mail is in a correct format (Example: mail@mail.com)",
                       "Email Format Error!", JOptionPane.WARNING_MESSAGE);
            } else {
               boolean found = roombooking.roomCheck(roomno, start + duration);
               boolean icexists = roombooking.icCheck(roomno, ic);
               if (found == true) {
                  lblError.setText("Error Occured");
                  lblError.setForeground(Color.RED);
               } else if (icexists == true) {
                  lblError.setText("User with same IC / Passport Number already exists");
                  lblError.setForeground(Color.RED);
               } else {
                  FileWriter fw = new FileWriter(roomno + ".txt", true);
                  BufferedWriter bw = new BufferedWriter(fw);
                  bw.write(String.valueOf(roomdates.getStart()));
                  bw.newLine();
                  bw.write(String.valueOf(roomdates.end()));
                  bw.newLine();
                  bw.write(roombooking.getName());
                  bw.newLine();
                  bw.write(roombooking.getIc());
                  bw.newLine();
                  bw.write(roombooking.getContact());
                  bw.newLine();
                  bw.write(roombooking.getEmail());
                  bw.newLine();

                  bw.close();
                  lblError.setForeground(Color.GREEN);
                  Font trb = new Font("TimesRoman", Font.BOLD, 18);
                  lblError.setFont(trb);
                  lblError.setText("Data has been added");
                  txtName.setText("");
                  txtIC.setText("");
                  txtContact.setText("");
                  txtEmail.setText("");
               }
            }
         }

      } catch (Exception e) {
         lblError.setText("Error : " + e);
         e.printStackTrace();
      }
   }//GEN-LAST:event_btnAddActionPerformed

   private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
      History a = new History();
      a.setVisible(true);
      this.dispose();
   }//GEN-LAST:event_btnHistoryActionPerformed

   private void txtICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtICKeyTyped
      boolean maxchar = txtIC.getText().length() > 12;
      if (maxchar) {
         evt.consume();
      }
   }//GEN-LAST:event_txtICKeyTyped

   private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
      boolean maxno = txtContact.getText().length() > 11;
      if (maxno) {
         evt.consume();
      }
   }//GEN-LAST:event_txtContactKeyTyped

   private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed
      char c = evt.getKeyChar();
      if (Character.isLetter(c)) {
         txtContact.setEditable(false);
      } else {
         txtContact.setEditable(true);
      }
   }//GEN-LAST:event_txtContactKeyPressed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Room().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdd;
   private javax.swing.JButton btnCheckRooms;
   private javax.swing.ButtonGroup btnGroupDays;
   private javax.swing.JButton btnHistory;
   private javax.swing.JComboBox<String> cmbDay;
   private javax.swing.JComboBox<String> cmbDuration;
   private javax.swing.JComboBox<String> cmbRoomNo;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JLabel lblError;
   private javax.swing.JTextField txtContact;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtIC;
   private javax.swing.JTextField txtName;
   // End of variables declaration//GEN-END:variables
}
